server {
    server_name nitrocalls.online www.nitrocalls.online;

    location / {
        root /var/www/html;
        index index.html;
        try_files $uri $uri/ /index.html;

        # Disable caching for index.html to force latest build
        if ($request_filename ~* \.html$) {
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        }
    }

    location /socket.io/ {
        proxy_pass http://127.0.0.1:5001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /translate {
        proxy_pass http://127.0.0.1:5001/translate;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/nitrocalls.online/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/nitrocalls.online/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.nitrocalls.online) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = nitrocalls.online) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name nitrocalls.online www.nitrocalls.online;
    return 404; # managed by Certbot
}
